### ISSUE TITLE
Restify Router Magic crash restify 7.x

### ISSUE THREAD

**Issue by frbuceta** [tests-always-included/restify-router-magic#5]
Restify only crash with restify router magic

[SEE RESTIFY ISSUE](https://github.com/restify/node-restify/issues/1646)

**Comment by fidian** [comment]
Is this an issue with `restify-router-magic` or with Restify itself? From what I see, this is an issue in Restify where they assume that something has a name. I assume they are hoping that a function has a name.

I don't think this module is at fault because the entire stack trace doesn't mention `restify-router-magic`.

**Comment by frbuceta** [comment]
I really do not know if it's `restify` or `restify-router-magic` problem... But when I use `restify-router-magic`, `restify 7.x` crash.
And is that I have not found the solution to this problem because with the minimum code crash

**Comment by fidian** [comment]
This looks like you have an error. You shouldn't pass a value to `next()`. Were you using an example somewhere that indicated you should do this?

```
// Wrong
next(res.send('hey'));

// Right
res.send('hey');
next();
```

When you pass anything to `next()`, it will assume it's an error in the middleware and immediately report the problem. The object returned from `res.send()` doesn't have a `name` property because it's not really an error that should be passed to `next()`.

Closing this issue. You should also probably close restify/node-restify#1646.
